### ISSUE TITLE
ac-php vs gtags

### ISSUE THREAD

**Issue by PauloPhagula** [aaronbieber/dotfiles#10]
In comparison to gtags I find that ac-php which comes with a  custom build ctags with extended PHP support, works better for PHP and recognizes namespaces well. 

From your blog I could infer you use your setup heavily with PHP and I noticed you use gtags for PHP. I wonder if you did any tweaks to gtags for PHP support?

**Comment by aaronbieber** [comment]
I did, in the past; I've all but left PHP behind at this point, but I recall looking at `ac-php` once before. For now, these areas of my config will remain neglected.

**Comment by PauloPhagula** [comment]
Alright, thanks!
