### ISSUE TITLE
Linkall line 92, "$dotfile" should be "$script"

### ISSUE THREAD

**Issue by dieggsy** [aaronbieber/dotfiles#3]
I know, I know, this is your personal dotfiles and it's not reeeally any of my business...

But I was looking around for inspiration on how to configure my own emacs.d and dotfiles folders, and I believe line 92 in `linkall`, which says:
`echo -n "Linking $dotfile -> $linkfile... "`
should say:
`echo -n "Linking $script -> $linkfile... "`
In order to properly display what is being symlinked in `bin`. May or may not be relevant or useful to you.

And btw you probably get this a fair bit and it's completely off topic, but you inspired me to check out evil mode (having originally learned the emacs keybindings), and it's pretty sweet to say the least! vim keybindings are so much more comfortable...

**Comment by aaronbieber** [comment]
I run this script maybe once a year or something, so I never noticed that mix-up, thanks!

Also glad you're enjoying Evil, it really is the best!
