### ISSUE TITLE
can not find such file

### ISSUE THREAD

**Issue by ramsayleung** [aaronbieber/dotfiles#4]
Hi Aaron,in the init-evil.el file ,it seems that there is no such a file called tiny-menu,and in you init.el ,the markdown-preview-template file name should be markdown-preview-template.html,but in the init.el file ,it is markdown-preview-template.html ,so Emacs could not find the file.Hope you can check it out

**Comment by aaronbieber** [comment]
Tiny Menu is now on MELPA, so you can change that to `(use-package tiny-menu :require t)` if you want to use it.

I don't have the markdown preview file thing working correctly; I have been trying to build a patch to submit to the project to allow for custom preview templates, but it is unfinished.

I strongly recommend starting your own configuration and pasting in the parts of mine that you like; my configuration is not guaranteed to work, and it is important that you understand how each part of your own configuration works.

**Comment by ramsayleung** [comment]
thanks for your reply. I have my own configuration   i am just curious about your configuration because i have watched you video in YouTube before and.just like you.  i used Vim before and i love it but now i change to emacs now. by the way. after trying your configuration, i wanna recommend you two packages (maybe you have used it ) ido and smex and expand religion. aha. it's three packages.
