### ISSUE TITLE
require or use-package?

### ISSUE THREAD

**Issue by ramsayleung** [aaronbieber/dotfiles#5]
Hi Aaran,it's me again .in your init.el file ,there is a statement that 

```
(require 'markdown-preview-mode )
```

but could not find this file in the emacs.d directory .do you mean **require** or **use-package**.
and i could not find a file named 'fence-edit'

```
(require 'fence-edit)
```

look forward to your reply

**Comment by aaronbieber** [comment]
This is my personal Emacs configuration, and so it will often be broken. I make changes and experiment all the time, and I very often push changes up to Github without fully testing them.

Fence Edit hasn't been submitted to MELPA yet, but you can get it from my Github.
