### ISSUE TITLE
error" Package php-extras " is unavailable

### ISSUE THREAD

**Issue by ramsayleung** [aaronbieber/dotfiles#6]
Alright,it is me again,Aaron,in your init.el ,there is a statement 

```
(use-package php-extras :ensure t :defer t)
```

but emacs raises an error that there  is no such a package,is there something wrong

**Comment by aaronbieber** [comment]
It is this package: https://github.com/arnested/php-extras

It is available from the Marmalade repository, which is configured in the `init-elpa.el` file. Something may be wrong with your `package.el` configuration, or the Marmalade repository was having problems at the time you attempted to load it.
